name: C++ Toolkit Doc Demo
markdown: kramdown
highlighter: pygments
safe: true
baseurl: /toolkitdocs
exclude: ['.ruby-version', 'node_modules', 'package.json', 'bower.json']
sass:
  sass_dir: static/_sass

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      organization-name: "NCBI - PubMed Labs"
      organization-url: "http://www.ncbi.nlm.nih.gov"
      organization-email: pubmedlabs@ncbi.nlm.nih.gov
      source-code-policy.url: 
